config/routes.rb
Rails.application.routes.draw do
  # Static pages
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'


  # User controller pages
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users do
    member do
      get :following, :followers
    end
  end

  # Sessions routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Account Activation routes
  resources :account_activations, only: [:edit]

  # Password Resets routes
  resources :password_resets, only: [:new, :create, :edit, :update]

  # Materials resource routes
  get '/upload', to: 'materials#new'
  post '/upload', to: 'materials#create'
  get '/search', to: 'materials#search_form'
  post '/materials', to: 'materials#search'
  get '/materials', to: 'materials#search'
  resources :materials do
    member do
      get :discussion
    end
  end

  # Relationships routes: create (follow), destroy (unfollow)
  resources :relationships, only: [:create, :destroy]

  # Topics routes
  get '/subtopic', to: 'topics#subtopic'
  get '/topic_search', to: 'topics#topic_search'
  resources :topics do
    member do
      get :discussion
    end
  end

  # Reviews routes
  resources :reviews, only: [:create, :new, :destroy]
  post '/review', to: 'reviews#new'
  get '/review', to: 'reviews#newdev'

  # Posts routes
  resources :posts, only: [:create, :show, :destroy]

  # Comments routes
  resources :comments, only: [:create, :destroy]


end

app/models/user.rb
class User < ApplicationRecord
  has_many :materials
  has_many :reviews
  has_many :comments, dependent: :destroy
  has_many :posts

  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships,  class_name: "Relationship",
                                     foreign_key: "followed_id",
                                     dependent: :destroy
  has_many :followers, through: :passive_relationships

  # Virtual attributes, not saved in db, sent to user
  attr_accessor :remember_token, :activation_token, :reset_token

  before_save { email.downcase! }

  before_create :create_activation_digest

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,  length: { maximum: 255 },
    format: { with:   VALID_EMAIL_REGEX},
    uniqueness: { case_sensitive: false }

  has_secure_password

  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  #METHODS

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  #Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sets the password reset attributes
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  # Sends password reset email
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Defines a proto-feed.
  # See "Following users" for the full implementation.
  def feed
    following_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    Material.where("user_id IN (#{following_ids}) OR user_id = :user_id",  user_id: id)
  end

  # Follows a user.
  def follow(other_user)
    following << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  private

    # Creates and assigns the activation token and digest
    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :index, :destroy, :following, :followers]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]

  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @materials = @user.materials.paginate(page: params[:page])
  end

  def new
    @user = User.new
    @subjects = Topic.where(ancestry: nil).map(&:name).sort
  end

  def create
    @user = User.new(user_params)
    topics = params[:topics]
    grades = params[:grades]
    if topics
      topics.each do |topic|
        topic_id = Topic.find_by(name: topic).id
        @user.topic_ids << topic_id
      end
    end
    if grades
      grades.each do |grade|
        @user.grades_taught << grade_convert(grade)
      end
    end
    if @user.save
      log_in @user
      @user.send_activation_email
      flash[:info] = "You are now logged in and ready to save and view materials.  Please check your email and activate your account in order to rate and upload materials."
      redirect_to @user
    else
      @subjects = Topic.where(ancestry: nil).map(&:name).sort
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    @subjects = Topic.where(ancestry: nil).map(&:name).sort
    grades = @user.grades_taught
    @grades = []
    grades.each do |grade|
      @grades << grade_reconvert(grade)
    end
    topic_ids = @user.topic_ids
    @subject_topics = {}
    @course_topics = []
    topic_ids.each do |topic_id|
      topic = Topic.find(topic_id)
      if topic.parent == nil
        @subject_topics[topic.name] = []
        topic.children.each do |child|
          @subject_topics[topic.name] << child.name
        end
      else
        @course_topics << topic.name
        if !@subject_topics.include?(topic.parent.name)
          @subject_topics[topic.parent.name] = []
          topic.parent.children.each do |child|
            @subject_topics[topic.parent.name] << child.name
          end
        end
      end
    end
    gon.subjects = @subject_topics
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      topics = params[:topics]
      grades = params[:grades]
      @user.topic_ids = []
      @user.grades_taught = []
      if topics
        topics.each do |topic|
          topic_id = Topic.find_by(name: topic).id
          @user.topic_ids << topic_id
        end
      end
      if grades
        grades.each do |grade|
          @user.grades_taught << grade_convert(grade)
        end
      end
      @user.save
      flash[:success] = "Profile updated"
      redirect_to home_path
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "user deleted"
    redirect_to users_path
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    # user_params prevent hackers from creating users with admin priveleges with command line calls to api
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
    def admin_user
      @user = current_user
      flash[:danger] = "nice try prick" unless current_user && current_user.admin?
      redirect_to(root_url) unless current_user && current_user.admin?
    end



end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def user_topics(topic_ids_array)
    topics = topic_ids_array.map do |topic_id|
      topic = Topic.find(topic_id)
      link_to topic.name, topic
    end
    topics.join(', ').html_safe
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="user_form col-xs-12">
  <%= form_for(@user, url: yield(:form_path)) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>


    <label for="grades_taught">Grades Taught</label>
    <div class="row grade_level">
      <div class="col-lg-3 col-md-3 col-sm-2 col-xs-2 col-xs-offset-1">
        <% grades = ['preK', 'K', '1st', '2nd', '3rd'] %>
        <% grades.each do |grade| %>
          <% if @grades %>
            <% ch = @grades.include?(grade) %>
          <% end %>
          <div class="grade_checkbox">
            <%= check_box_tag('grades[]', grade, nil, {multiple: true, id: grade, checked: ch }) %>
            <label for="<%= grade %>"> <%= grade %> </label>
          </div>
        <% end %>
      </div>
      <div class="col-lg-3 col-md-3 col-sm-2 col-xs-2">
        <% grades = ['4th', '5th', '6th', '7th', '8th'] %>
        <% grades.each do |grade| %>
          <% if @grades %>
            <% ch = @grades.include?(grade) %>
          <% end %>
          <div class="grade_checkbox">
            <%= check_box_tag('grades[]', grade, nil, {multiple: true, id: grade, checked: ch }) %>
            <label for="<%= grade %>"> <%= grade %> </label>
          </div>
        <% end %>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-2 col-xs-2">
        <% grades = ['9th', '10th', '11th', '12th'] %>
        <% grades.each do |grade| %>
          <% if @grades %>

            <% ch = @grades.include?(grade) %>
          <% end %>
          <div class="grade_checkbox">
            <%= check_box_tag('grades[]', grade, nil, {multiple: true, id: grade, checked: ch }) %>
            <label for="<%= grade %>"> <%= grade %> </label>
          </div>
        <% end %>
      </div>
    </div>
    <label for="topic_ids">Subjects Taught</label>
      <div class="user_topics">
        <% @subjects.each do |subject| %>
          <div class="topic_checkbox">
            <% if @subject_topics %>
              <% ch = @subject_topics.keys.include?(subject) %>
            <% end %>
            <%= check_box_tag('topics[]', subject, nil, {multiple: true, id: subject, checked: ch}) %>
            <label for="<%= subject %>"> <%= subject %> </label>
          </div>
        <% end %>
      </div>

      <div class="user_courses">
        <% if @subject_topics %>
          <% @subject_topics.keys.each do |subject| %>
            <div id="<%= subject.sub(' ', '') %>_div">
              <label><%= subject %> Courses Taught</label>
              <div class="user_topics">
                <% @subject_topics[subject].each do |course| %>
                  <% if @course_topics %>
                    <% ch = @course_topics.include?(course) %>
                  <% end %>
                  <div class="topic_checkbox">
                    <%= check_box_tag('topics[]', course, nil, {multiple: true, id: course, checked: ch}) %>
                    <label for="<%= course %>"> <%= course %> </label>
                  </div>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>



    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <% end %>
</div>

<%= javascript_include_tag 'user_form' %>

app/views/users/_home.html.erb
<div class="user_home">
  <div class="row">
    <div class="hidden-sm hidden-md hidden-lg">
      <h2>Welcome Back, <%= @user.name %> </h2>
    </div>
    <div class="col-sm-4 col-lg-3 hidden-xs">
      <h2>Welcome Back, <%= @user.name %> </h2>
      <section class="user_info">
          <%= link_to gravatar_for(@user), @user %>
          <%= link_to 'Your Profile', @user %>
      </section>
      <%= render 'shared/activity' %>
    </div>
    <div class="col-sm-8 col-lg-9 col-xs-12">
      <% if @course_materials %>
        <h3>New Materials in Your Courses:</h3>
        <div class="row following_materials">
          <%= render partial: 'shared/home_material_card', collection: @course_materials, as: :material %>
        </div>
      <% else %>
        <div class="home_user_alert">
          <%= link_to "Update your profile", edit_user_path(current_user) %> with the courses you teach to see new materials from those courses here.
        </div>
      <% end %>
      <% if @following_materials %>
        <h3>New Materials From Users You Follow:</h3>
        <div class="row following_materials">
          <%= render partial: 'shared/home_material_card', collection: @following_materials, as: :material %>
        </div>
      <% else %>
        <div class="home_user_alert">
          <%= link_to "Follow other users", users_path %> to see their new materials here.
        </div>
      <% end %>
        <div class="home_user_alert">
          Comments on your discussion threads here.
        </div>
    </div>
  </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && current_user != (user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:button_text, "Save changes") %>
<% provide(:form_path, user_path) %>

<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="row">
      <%= render 'form' %>
    </div>
    <br/>
    <div class="row gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>
<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, "Create my account") %>
<% provide(:form_path, signup_path) %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= render  'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <%= render 'follow_form' if logged_in? %>
  </aside>
  <div class="col-md-8">

    <% if @user.materials.any? %>
      <h3> Materials shared (<%= @user.materials.count %>)</h3>
      <ol class="materials">
        <%= render @materials %>
      </ol>
      <%= will_paginate @materials %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Materials shared:</b> <%= @user.materials.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>