config/routes.rb
Rails.application.routes.draw do
  # Static pages
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'


  # User controller pages
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users do
    member do
      get :following, :followers
    end
  end

  # Sessions routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Account Activation routes
  resources :account_activations, only: [:edit]

  # Password Resets routes
  resources :password_resets, only: [:new, :create, :edit, :update]

  # Materials resource routes
  get '/upload', to: 'materials#new'
  post '/upload', to: 'materials#create'
  get '/search', to: 'materials#search_form'
  post '/materials', to: 'materials#search'
  get '/materials', to: 'materials#search'
  resources :materials do
    member do
      get :discussion
    end
  end

  # Relationships routes: create (follow), destroy (unfollow)
  resources :relationships, only: [:create, :destroy]

  # Topics routes
  get '/subtopic', to: 'topics#subtopic'
  get '/topic_search', to: 'topics#topic_search'
  resources :topics do
    member do
      get :discussion
    end
  end

  # Reviews routes
  resources :reviews, only: [:create, :new, :destroy]
  post '/review', to: 'reviews#new'
  get '/review', to: 'reviews#newdev'

  # Posts routes
  resources :posts, only: [:create, :show, :destroy]

  # Comments routes
  resources :comments, only: [:create, :destroy]


end

app/views/shared/_activity.html.erb
<div class="user_activity">
  <h4>Recently Viewed Materials:</h4>

    <%= render partial: 'shared/similar_material_card', collection: @recent_views, as: :material %>

</div>

app/views/shared/_discussion.html.erb
<%= render 'shared/new_post_form' %>
<% if @posts.any? %>
  <%= render @posts %>
<% else %>
  <p>There are no posts about this <%= yield(:discussion_type) %> yet. </p>
<% end %>  

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_first_review_form.html.erb
<div class="row">
  <%= form_for(@review, url: first_review_path) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= hidden_field(:material, :id) %>
    <%= hidden_field(:review, :overall_rating, :value => 5) %>
    <div class="col-lg-4 col-md-4 col-sm-4">
      <ul>
        <br/>
        <li><strong>Material Title: </strong><%= @material.title %></li>
        <li><strong>Content type: </strong><%= @material.content_type %> </li>
        <li><strong>Course: </strong><%= @material.topic.parent.name %></li>
        <li><strong>Topic: </strong><%= @material.topic.name %> </li>
        <% if @material.link && !@material.link.empty? %>
          <li><strong>Link: </strong><%= link_to @material.title, @material.link %> </li>
        <% end %>
        <% if @material.files.any? %>
          <li><strong>Files: </strong><%= @material.files.length %> </li>
        <% end %>
        <% if @material.time_required && !@material.time_required.empty? %>
          <li><strong>Length: </strong><%= @material.time_required %> minutes </li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-8 col-sm-8 col-lg-8 review_form">
      <div class="row review_grade_levels">
        <div class="col-md-10 col-sm-10 col-xs-12 col-lg-10">
          <label for="review_grade_level_bottom">
            Grade Level:
          </label>
          <p>
            This material is suitable for students from grades
            <%= f.select :grade_level_bottom, (1..12).to_a.unshift("preK", 'K') %>
            to
            <%= f.select :grade_level_top, (1..12).to_a.unshift("preK", 'K'), :selected => '12'%>
          </p>
        </div>
      </div>
      <div class="row review_time_required">
        <div class="col-md-10 col-sm-10 col-xs-12 col-lg-10">
          <label for="review_time_required">
            Time Required:
          </label>
          <%= hidden_field :review, :time_required %>
          <p>
            <%= f.select :hours, (0..12).to_a %> hours and
            <%= f.select :minutes, (0..55).step(5).to_a %> minutes
          </p>
        </div>
      </div>
      <div class="row review_suggestions">
        <div class="col-md-10 col-sm-10 col-xs-12 col-lg-10">
          <label for="review_suggestions">
            Suggestions for this Material:
          </label>
          <%= f.text_area :suggestions %>
        </div>
      </div>
      <div class="row review_submit">
        <div class="col-md-8 col-sm-8 col-xs-8 col-xs-offset-2 col-lg-6">
          <%= f.submit "Submit", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= javascript_include_tag 'review_form' %>

app/views/shared/_home_material_card.html.erb
<div class="home_material">
  <div class="row home_material_title">
    <h3>
      <%= link_to truncate(material.title, length: 40), material %>
    </h3>
  </div>
  <div class="row home_material_content_type_icon">
    <p>
      <%= link_to image_tag("#{material.content_type}.svg"), material %>
    </p>
    <p>
      <%= link_to material.content_type, material %>
    </p>
  </div>
  <div class="row home_material_content_type">
    <em>
      <%= link_to truncate(material.topic.parent.parent.name, length: 20), material.topic.parent.parent %> >>
      <%= link_to truncate(material.topic.parent.name, length: 20), material.topic.parent %> >>
      <%= link_to truncate(material.topic.name, length: 20), material.topic %>
    </em>
  </div>
  <div class="row home_material_user">
    Shared <%= time_ago_in_words(material.created_at) %> ago by <%= link_to material.user.name, material.user %>
  </div>


</div>
&ensp;

app/views/shared/_material_form2.html.erb
<div class="row">
  <%= form_for(@material, url: '/upload2') do |f| %>
  <%= hidden_field(:material, :id) %>
  <%= hidden_field(:material, :title) %>
  <%= render 'shared/error_messages', object: f.object %>
    <div class="col-lg-4 col-md-4 col-sm-4">
      <ul>
        <br/>
        <li><strong>Material Title: </strong><%= @material.title %></li>
        <li><strong>Content type: </strong><%= @material.content_type %> </li>
        <li><strong>Course: </strong><%= @material.topic.parent.name %></li>
        <li><strong>Topic: </strong><%= @material.topic.name %> </li>
        <% if !@material.link.empty? %>
          <li><strong>Link: </strong><%= link_to @material.title, @material.link %> </li>
        <% end %>
        <% if !@material.time_required.nil? %>
          <li><strong>Length: </strong><%= @material.time_required %> minutes </li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-8 col-sm-8 col-lg-8">
      <div class="row">
        <div class="col-md-10 col-sm-10 col-xs-12 col-lg-10">
          <div class="material_files">
            <label for="files">Choose file(s) to upload with this material:</label>
            <%= f.file_field :files, multiple: true , accept: 'image/*,.doc, .docx,.ppt, .pptx,.txt,.pdf,.odt'%>
          </div>
          <div>
            <ul class="file_preview_list">

            </ul>

          </div>
        </div>
      </div>
      <div class="material_link">
        <div class="row">
          <div class="col-md-10 col-sm-10 col-xs-12 col-lg-10">
            <label for="link">Link:</label>
            <%= f.url_field :link, class: 'form-control', placeholder:'Enter the web address of material you would like to share'%>
          </div>
        </div>

      </div>

      <div class="row">
        <div class="material_keywords col-md-10 col-sm-10 col-xs-12 col-lg-10">
          <label for="keywords">Select applicable keywords:</label>
          <div class="keywords_list">
            <% @top_keywords.each do |keyword| %>
              <div class="keyword_item">
                <%= f.check_box :keywords, { :multiple => true, id: keyword }, keyword  %>
                <label for="<%= keyword %>"> <%= keyword %> </label>
              </div>
            <% end %>
            <p>
              Other Keywords:
              <%= text_field_tag(:other_keywords) %>
            </p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="material_summary col-md-10 col-sm-10 col-xs-12 col-lg-10">
          <label for="summary">Write a brief summary of this material:</label>
          <%= f.text_area :summary, class: 'form-control', placeholder: "Write a brief summary of this material" %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8 col-sm-8 col-xs-8 col-xs-offset-2 col-lg-6">
          <%= f.submit "Next Page", class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>
</div>


<%= javascript_include_tag 'material_form2' %>

app/views/shared/_material_summary_box.html.erb
<div class="row material_summary_box">
  <div class="col-lg-5 col-md-6 col-sm-6 col-xs-8">
    <ul>
      <li>
        <!-- note: width px is hardcoded to fit height px (see custom.css) -->
        <% if @material.reviews.any? %>
          <div class="material_rating">
            <span class="five_stars" style="width:<%= @material.average_rating/5 * 97 %>px"></span>
            <span class="zero_stars" style="width:<%= (5-@material.average_rating)/5 * 97 %>px; background:<% @material.average_rating/5 * 97 %>px"></span>
            (<em>Average rating: </em><%= @material.average_rating %>/5)
          </div>
        <% end %>
      </li>
      <li>
        <em>
          <%= link_to @material.topic.parent.parent.name, @material.topic.parent.parent %> >>
          <%= link_to @material.topic.parent.name, @material.topic.parent %> >>
          <%= link_to @material.topic.name, @material.topic %>
        </em>
      </li>
    </ul>
  </div>
  <div class="col-lg-5 col-md-6 col-sm-6 col-xs-6">
    <ul>
      <li>
        <p>
          Average Time:
          <span class="material_summary_fill">
            <%= time_convert(@material.time_required) %>
          </span>
        </p>
      </li>
      <li>
        <p>
            Grade Level:
          <span class="material_summary_fill">
            <%= @material.grade_level %>
          </span>
        </p>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_new_post_form.html.erb
<div class="new_post_form">
  <% if current_user %>
    <div id="post_prompt">
      <p>➕ Post a question or comment about this <%= yield(:discussion_type) %></p>
    </div>
    <div id="post_form" class="hidden">
      <% if yield(:discussion_type) == 'material' %>
        <%= form_for(@material.posts.build) do |f| %>
          <%= hidden_field_tag :postable_type, 'material' %>
          <%= hidden_field_tag :material_id, @material.id %>
          <div class="new_post_input input-group">
            <%= f.text_area :content, placeholder: "Type question or comment here." %>
            <%= f.submit "Post" %>
          </div>
        <% end %>
      <% elsif yield(:discussion_type) == 'topic' %>
      <%= form_for(@topic.posts.build) do |f| %>
        <%= hidden_field_tag :postable_type, 'topic' %>
        <%= hidden_field_tag :topic_id, @topic.id %>
        <div class="new_post_input input-group">
          <%= f.text_area :content, placeholder: "Type question or comment here." %>
          <%= f.submit "Post" %>
        </div>
      <% end %>
      <% end %>
    </div>
  <% else %>
    <div class="login_register">
      <%= link_to "Log in", login_path %> or <%= link_to "register", signup_path %> to post on this discussion.
    </div>

  <% end %>

</div>

app/views/shared/_similar_material_card.html.erb
<div class="similar_material">
  <a href="<%= material_path(material) %>">
    <div class="row material_show_title_rating_button">
      <div class="col-md-2 col-lg-2 col-sm-3 content_type_icon">
        <div class="material_content_type_icon">
          <p>
            <%=  image_tag("#{material.content_type}.svg", :class => "center-block") %>
          </p>
          <p>
            <%= material.content_type %>
          </p>
        </div>
      </div>
      <div class="col-md-10 col-lg-10 col-sm-9 material_show_title">
        <h3>
          <span class="material-title">
            <%= material.title %>
          </span>
        </h3>
      </div>
    </div>
    <div class="row material_summary_box">
      <ul>
        <li>
          <!-- note: width px is hardcoded to fit height px (see custom.css) -->
          <% if material.average_rating %>
            <div class="material_rating">
              <span class="five_stars" style="width:<%= material.average_rating/5 * 77.8 %>px"></span>
              <span class="zero_stars" style="width:<%= (5 - material.average_rating)/5 * 77.8 %>px; background:<% material.average_rating/5 * 77.8 %>px"></span>
              </div>
          <% end %>
        </li>
        <li class="hidden-sm">
          <em>
            <%= material.topic.parent.parent.name %> >>
            <%= material.topic.parent.name %> >>
            <%= material.topic.name %>
          </em>
        </li>
        <li class="hidden-sm">
          Average Time: <%= time_convert(material.time_required) %>
        </li>
        <li >
          Grade Level: <%= material.grade_level %>
        </li>
      </ul>
    </div>
  </a>
</div>
<br/>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <ul>
    <% if @user.grades_taught.any? %>
      <li>
        <span class="stat_label">Grades Taught: </span><%= grades_display(@user.grades_taught) %>
      </li>
    <% end %>
    <% if @user.topic_ids.any? %>
      <li>
        <span class="stat_label">Topics Taught: </span><%= user_topics(@user.topic_ids) %>
      </li>
    <% end %>
    <li>
        <span class="stat_label">Materials Shared: </span><%= @user.materials.count %>
      </li>


      <li>
        <span class="stat_label">Posts: </span><%= @user.posts.count %>
      </li>


      <li>
        <span class="stat_label">Comments: </span><%= @user.comments.count %>
      </li>

    <li>
      <a href="<%= following_user_path(@user) %>">
        <strong id="following" class="stat">
          <%= @user.following.count %>
        </strong>
        following
      </a>
      <a href="<%= followers_user_path(@user) %>">
        <strong id="followers" class="stat">
          <%= @user.followers.count %>
        </strong>
        followers
      </a>
    </li>
  </ul>

</div>

app/views/shared/_topic_box.html.erb
<div class="topic_box">
  <ul>
    <li>
      <span class="topic_label">
        Subject:
      </span>
      <span class="topic_fill">
        <%= @material.topic.parent.parent.name %>
      </span>
    </li>
    <li>
      <span class="topic_label">
        Course:
      </span>
      <span class="topic_fill">
        <%= @material.topic.parent.name %>
      </span>
    </li>
    <li>
      <span class="topic_label">
        Topic:
      </span>
      <span class="topic_fill">
        <%= @material.topic.name %>
      </span>
    </li>
  </ul>
</div>

app/views/shared/_topic_material_card.html.erb
<div class="topic_material">
  <a href="<%= material_path(material) %>">
    <h3>
      <%= material.title %>
    </h3>
    <span class="material_rating">
      <ul>
        <li>
          <!-- note: width px is hardcoded to fit height px (see custom.css) -->
          <% if material.average_rating %>
            <span class="five_stars" style="width:<%= material.average_rating/5 * 77.8 %>px"></span>
            <span class="zero_stars" style="width:<%= (5 - material.average_rating)/5 * 77.8 %>px; background:<% material.average_rating/5 * 77.8 %>px"></span>
          <% end %>
        </li>
      </ul>
    </span>
      <p>Grade Level: <%= material.grade_level %></p>

  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.materials.count, "material") %></span>