config/routes.rb
Rails.application.routes.draw do
  # Static pages
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'


  # User controller pages
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users do
    member do
      get :following, :followers
    end
  end

  # Sessions routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Account Activation routes
  resources :account_activations, only: [:edit]

  # Password Resets routes
  resources :password_resets, only: [:new, :create, :edit, :update]

  # Materials resource routes
  get '/upload', to: 'materials#new'
  post '/upload', to: 'materials#create'
  get '/search', to: 'materials#search_form'
  post '/materials', to: 'materials#search'
  get '/materials', to: 'materials#search'
  resources :materials do
    member do
      get :discussion
    end
  end

  # Relationships routes: create (follow), destroy (unfollow)
  resources :relationships, only: [:create, :destroy]

  # Topics routes
  get '/subtopic', to: 'topics#subtopic'
  get '/topic_search', to: 'topics#topic_search'
  resources :topics do
    member do
      get :discussion
    end
  end

  # Reviews routes
  resources :reviews, only: [:create, :new, :destroy]
  post '/review', to: 'reviews#new'
  get '/review', to: 'reviews#newdev'

  # Posts routes
  resources :posts, only: [:create, :show, :destroy]

  # Comments routes
  resources :comments, only: [:create, :destroy]


end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :postable, polymorphic: true
  has_many :comments, as: :commentable
  validates :content, presence: true
  default_scope -> { order(created_at: :desc) }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def create
    if params[:postable_type] == 'material'
      material = Material.find(params[:material_id])
      @post = material.posts.build(post_params)
    else
      topic = Topic.find(params[:topic_id])
      postable = topic
      @post = topic.posts.build(post_params)
    end
    @post.user = current_user
    if @post.save
      if params[:postable_type] == 'material'
        redirect_to material
      else
        redirect_to topic
      end
    else
      flash[:danger] = "Post not saved."
      if params[:postable_type] == 'material'
        redirect_to material
      else
        redirect_to topic
      end
    end
  end

  def show
    @post = Post.find(params[:id])
    @postable = @post.postable
    @comments = @post.comments.order(:created_at)
  end

  def destroy
  end


  private
  def post_params
    params.require(:post).permit(:content)
  end


end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<% if !post.content.nil? && !post.content.empty? %>
<div class="post_card">
  <div class="post_comment_count">
    <%= link_to post.comments.count, post %>
  </div>
  <div class="post_content">
    <h3><%= link_to truncate(post.content, length: 150), post %></h3>
  </div>
  <div class="post_user_info">
    Posted by <%= link_to post.user.name, post.user %> <%= time_ago_in_words(post.created_at) %> ago.
    <% if post.comments.any? %>
      Most recent comment by  <%= link_to post.comments.last.user.name, post.comments.last.user %> <%= time_ago_in_words(post.comments.last.created_at) %> ago.
    <% else %>
      No comments yet.
    <% end %>
  </div>

</div>
<% end %>

app/views/posts/show.html.erb
<% provide(:title, truncate(@post.content, length: 40)) %>

<div class="row post_show">
  <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
    <div class="row post_postable_type">
      <p>
        <% if @post.postable_type == 'Material' %>
          <a href="<%= discussion_material_path(@postable) %>">
            ⬅ Back to discussion for <u><%= @post.postable.title %></u>
          </a>
        <% elsif @post.postable_type == 'Topic' %>
          <a href="<%= discussion_topic_path(@postable) %>">
            ⬅ Back to discussion for <u><%= @post.postable.name %></u>
          </a>
        <% end %>
      </p>
    </div>
    <div class="row post_content">
      <h1><%= @post.content %></h1>
      <span class="post_user">
        Posted by <%= link_to @post.user.name, @post.user %> <%= time_ago_in_words(@post.created_at) %> ago.
      </span>
      <span class="post_follow_button">
        <%= link_to 'Follow this dicussion' %>
      </span>
    </div>
    <div class="row post_comments">
      <% if @post.comments.any? %>
        <%= render @comments %>
      <% else %>
        <br/>
        <span class="no_comments">  <p><em>There are no comments for this post yet.</em></p>
        </span>
        <br/>
      <% end %>
    </div>
    <div class="row comment_form">
      <% if current_user %>
        <h1>Add a comment to this discussion:</h1>
        <p>Posting as <%= link_to current_user.name, current_user %></p>
        <%= form_for(@post.comments.build) do |f| %>
          <%= hidden_field_tag :post_id, @post.id %>
          <div class="new_comment_input">
            <%= f.text_area :content, placeholder: "Type comment here." %>
            <%= f.submit "Comment" %>
          </div>
        <% end %>
      <% else %>
        <%= link_to "Log in", login_path %> or <%= link_to "register", signup_path %> to comment on this post.
      <% end %>
    </div>
  </div>
</div>