config/routes.rb
Rails.application.routes.draw do
  # Static pages
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'


  # User controller pages
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users do
    member do
      get :following, :followers
    end
  end

  # Sessions routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Account Activation routes
  resources :account_activations, only: [:edit]

  # Password Resets routes
  resources :password_resets, only: [:new, :create, :edit, :update]

  # Materials resource routes
  get '/upload', to: 'materials#new'
  post '/upload', to: 'materials#create'
  get '/search', to: 'materials#search_form'
  post '/materials', to: 'materials#search'
  get '/materials', to: 'materials#search'
  resources :materials do
    member do
      get :discussion
    end
  end

  # Relationships routes: create (follow), destroy (unfollow)
  resources :relationships, only: [:create, :destroy]

  # Topics routes
  get '/subtopic', to: 'topics#subtopic'
  get '/topic_search', to: 'topics#topic_search'
  resources :topics do
    member do
      get :discussion
    end
  end

  # Reviews routes
  resources :reviews, only: [:create, :new, :destroy]
  post '/review', to: 'reviews#new'
  get '/review', to: 'reviews#newdev'

  # Posts routes
  resources :posts, only: [:create, :show, :destroy]

  # Comments routes
  resources :comments, only: [:create, :destroy]


end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Teachable
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-light">
    <nav>
      <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">

        <!-- Button that toggles the navbar on and off on small screens -->
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">

        <!-- Hides information from screen readers -->
          <span class="sr-only"></span>

          <!-- Draws 3 bars in navbar button when in small mode -->
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <ul class="nav navbar-nav navbar-left">
        <li>
          <%= link_to "Teachable", root_path, id: "logo", class: "hidden-xs nav" %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right collapse navbar-collapse" id="navbar-collapse-1">
        <li>
          <div class="nav navbar-nav navbar-center">

              <%= form_tag("/materials", method: "post", class:"navbar-form hidden-xs") do %>
                <div class="input-group">
                  <%= text_field_tag :search_terms, nil, placeholder: "Search for materials", class:"form-control" %>
                  <div class="input-group-btn">
                    <%= button_tag class: 'btn btn-default' do %>
                      <i class="glyphicon glyphicon-search"></i>
                    <% end %>
                  </div>
                </div>
              <% end %>
          </div>
        </li>
        <li><%= link_to "Search", search_path, class:"hidden-md hidden-sm hidden-lg" %></li>
    

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Browse <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Materials", materials_path %></li>
            <li><%= link_to "Subjects", topics_path %></li>
          </ul>
        </li>
        <% if logged_in? %>
          <li><%= link_to "Upload", upload_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Your Profile", current_user %></li>
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: :delete %></li>
            </ul>
          </li>

        <% else %>
          <li><%= link_to "Register", signup_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>

      </ul>

    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= Gon::Base.render_data %>
    <%= include_gon %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>